name: CI

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  playframework-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    
    - name: Cache sbt
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - name: Run tests
      run: sbt test
    
    - name: Compile
      run: sbt compile