name: CI

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  playframework-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    
    - name: Cache sbt
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    #- name: Run tests
    #  run: sbt test
    
    - name: Compile
      run: sbt compile
    
    - name: Start application
      run: |
        sbt "run 9000" &
        echo "Waiting for application to start..."
        for i in {1..60}; do
          if curl -s http://localhost:9000/ > /dev/null 2>&1; then
            echo "Application started successfully after $i seconds"
            break
          fi
          echo "Attempt $i: Application not ready yet, waiting..."
          sleep 5
        done
    
    - name: Test application endpoint
      run: |
        curl -f http://localhost:9000/ || exit 1
        echo "Application is running successfully"
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Take screenshot
      run: |
        google-chrome --headless --disable-gpu --no-sandbox --screenshot=screenshot.png --window-size=1280,720 http://localhost:9000/
        ls -la screenshot.png
    
    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: application-screenshot
        path: screenshot.png